# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nsimon <nsimon@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/04 01:56:24 by nsimon            #+#    #+#              #
#    Updated: 2020/01/04 02:02:06 by nsimon           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


SRCS	    = 	ft_printf.c\
				ft_printf_pointer.c\
				ft_printf_simple.c\
				ft_printf_uint.c

PRE		    =	./srcs/

SRC			= 	${addprefix ${PRE}, ${SRCS}}

BONUS_SRC	=	${addprefix ${PRE}, ${BONUS_SRCS}}

OBJS		= 	${SRC:.c=.o}

BONUS_OBJS	=	${BONUS_SRCS:.c=.o}

HEADERS		= 	./include/

LIB_DIR		=	./libft

LIB_NAME	=	ft

NAME		= 	libftprintf.a

CC			= 	gcc

CFLAGS		= 	-L${LIB_DIR} -l${LIB_NAME} -Wall -Wextra -Werror

RM			= 	rm -f

.c.o:
			${CC} ${CFLAGS} -I ${HEADERS} -c $< -o ${<:.c=.o}

$(NAME):	${OBJS}
			ar rc ${NAME} ${OBJS}
			ranlib ${NAME}

all:		${NAME}

clean:
			${RM} ${OBJS} ${BONUS_OBJS}

fclean:		clean
			${RM} ${NAME}

re:			fclean all

bonus:		${BONUS_OBJS}
			ar rc ${NAME} ${BONUS_OBJS}
			ranlib ${NAME}


.PHONY: all clean fclean re bonus
